// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuTIeq8uY4sOURHeoUO9j2Wx4p_AlghU8',
    appId: '1:48694251061:web:6677c5276edafddf992b7c',
    messagingSenderId: '48694251061',
    projectId: 'casoiko-labs',
    authDomain: 'casoiko-labs.firebaseapp.com',
    storageBucket: 'casoiko-labs.firebasestorage.app',
    measurementId: 'G-QZX3G8BQLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-P__mtkhM6ayC36bGx5HlcznWeDvfbEQ',
    appId: '1:48694251061:android:b5903dd90a9227d4992b7c',
    messagingSenderId: '48694251061',
    projectId: 'casoiko-labs',
    storageBucket: 'casoiko-labs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTtRPyOfqo-yoQ9Ibu-31hzXZtviKlwqE',
    appId: '1:48694251061:ios:9034ec4cf066af81992b7c',
    messagingSenderId: '48694251061',
    projectId: 'casoiko-labs',
    storageBucket: 'casoiko-labs.firebasestorage.app',
    iosBundleId: 'com.casoiko.casoiko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTtRPyOfqo-yoQ9Ibu-31hzXZtviKlwqE',
    appId: '1:48694251061:ios:9034ec4cf066af81992b7c',
    messagingSenderId: '48694251061',
    projectId: 'casoiko-labs',
    storageBucket: 'casoiko-labs.firebasestorage.app',
    iosBundleId: 'com.casoiko.casoiko',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuTIeq8uY4sOURHeoUO9j2Wx4p_AlghU8',
    appId: '1:48694251061:web:e5a8086521c910f2992b7c',
    messagingSenderId: '48694251061',
    projectId: 'casoiko-labs',
    authDomain: 'casoiko-labs.firebaseapp.com',
    storageBucket: 'casoiko-labs.firebasestorage.app',
    measurementId: 'G-DH4P8GB9Q8',
  );
}
