// File generated by FlutterFire CLI / flutterfire configure.
//
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions não configurado para esta plataforma. '
          'Rode: dart pub global activate flutterfire_cli && flutterfire configure',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnGKcBOg-TRIVTsea00GCmovrZX5VXAzE',
    appId: '1:1029739013854:web:2758c473700aea78af044f',
    messagingSenderId: '1029739013854',
    projectId: 'natipsico-bef4d',
    authDomain: 'natipsico-bef4d.firebaseapp.com',
    storageBucket: 'natipsico-bef4d.firebasestorage.app',
    measurementId: 'G-GVSPKDD6DV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7GBuWojn5Ofk0Aumyv386_eD0YlieYBw',
    appId: '1:1029739013854:android:ec4e693cf6af762baf044f',
    messagingSenderId: '1029739013854',
    projectId: 'natipsico-bef4d',
    storageBucket: 'natipsico-bef4d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWBCvYe4wELMdQc8U5h4PVG8nqcR23Kgc',
    appId: '1:1029739013854:ios:9716beb5ae103ef5af044f',
    messagingSenderId: '1029739013854',
    projectId: 'natipsico-bef4d',
    storageBucket: 'natipsico-bef4d.firebasestorage.app',
    androidClientId: '1029739013854-hnlhjigsbfvfjn9nu06gsrh8s490gtce.apps.googleusercontent.com',
    iosClientId: '1029739013854-fas9e1loesu8ei33jjoeft4c5fmdrdk8.apps.googleusercontent.com',
    iosBundleId: 'com.rafael.natipsico',
  );
}
