#!/usr/bin/env node
/**
 * Build completo: Natalia Farias — Psicologia (demo designer + MCP parity)
 */
import {
  createComponentFromNodes,
  createInstance,
  createScreen,
  cryptoRandomId,
  readBoard,
  scrubBoardRefs,
  syncAllComponentDefs,
  writeBoard,
  resolveProjectBoardPath,
} from '../packages/core/src/index.js';

const PROJECT_ID = process.env.NATALIA_PROJECT_ID || 'id_8aa2a1ba';
const path = resolveProjectBoardPath(PROJECT_ID);

const C = {
  bg: '#FAF8F5',
  sage: '#5C7C6F',
  sageDark: '#3D5A50',
  sageLight: '#E8F0EC',
  sand: '#C4A882',
  text: '#2C3338',
  muted: '#6B7280',
  white: '#FFFFFF',
  border: '#E5E7EB',
};

const screensMeta = [
  { id: 'nat_welcome', name: '01 — Boas-vindas', x: 0 },
  { id: 'nat_home', name: '02 — Início', x: 470 },
  { id: 'nat_about', name: '03 — Sobre', x: 940 },
  { id: 'nat_services', name: '04 — Serviços', x: 1410 },
  { id: 'nat_book', name: '05 — Agendar', x: 1880 },
  { id: 'nat_contact', name: '06 — Contato', x: 2350 },
];

let board = {
  version: 2,
  revision: 0,
  screens: [],
  components: [],
  prototypes: [],
  comments: [],
};

for (const s of screensMeta) {
  board.screens.push(
    createScreen({
      id: s.id,
      name: s.name,
      x: s.x,
      y: 0,
      width: 390,
      height: 844,
      background: C.bg,
      board,
    }),
  );
}

const [welcome, home, about, services, book, contact] = board.screens;

welcome.nodes = [
  {
    id: 'w_hero',
    type: 'rect',
    x: 0,
    y: 0,
    w: 390,
    h: 420,
    fill: C.sage,
    bottomRadius: 32,
    name: 'Hero',
  },
  {
    id: 'w_circle',
    type: 'rect',
    x: 135,
    y: 120,
    w: 120,
    h: 120,
    fill: C.sageLight,
    cornerRadius: 60,
    name: 'Avatar',
  },
  {
    id: 'w_initials',
    type: 'text',
    x: 135,
    y: 165,
    w: 120,
    h: 40,
    text: 'NF',
    fontSize: 36,
    fontWeight: 700,
    color: C.sageDark,
    align: 'center',
    name: 'Iniciais',
  },
  {
    id: 'w_name',
    type: 'text',
    x: 24,
    y: 460,
    w: 342,
    h: 44,
    text: 'Natalia Farias',
    fontSize: 32,
    fontWeight: 700,
    color: C.text,
    name: 'Nome',
  },
  {
    id: 'w_role',
    type: 'text',
    x: 24,
    y: 508,
    w: 342,
    h: 28,
    text: 'Psicóloga · Terapia individual e online',
    fontSize: 15,
    color: C.muted,
    name: 'Cargo',
  },
  {
    id: 'w_quote_bg',
    type: 'rect',
    x: 24,
    y: 560,
    w: 342,
    h: 88,
    fill: C.sageLight,
    cornerRadius: 16,
    name: 'Quote bg',
  },
  {
    id: 'w_quote',
    type: 'text',
    x: 40,
    y: 578,
    w: 310,
    h: 52,
    text: 'Cuidar da mente é um ato de coragem e autocuidado.',
    fontSize: 14,
    color: C.sageDark,
    name: 'Frase',
  },
  {
    id: 'w_cta',
    type: 'button',
    x: 24,
    y: 680,
    w: 342,
    h: 56,
    label: 'Conhecer meu trabalho',
    fill: C.sage,
    textColor: C.white,
    cornerRadius: 16,
    fontSize: 16,
    fontWeight: 600,
    name: 'CTA primário',
  },
  {
    id: 'w_cta2',
    type: 'button',
    x: 24,
    y: 748,
    w: 342,
    h: 52,
    label: 'Agendar consulta',
    fill: C.white,
    textColor: C.sage,
    cornerRadius: 16,
    fontSize: 15,
    fontWeight: 600,
    stroke: C.sage,
    strokeWidth: 1.5,
    name: 'CTA secundário',
  },
];

home.nodes = [
  {
    id: 'h_header',
    type: 'rect',
    x: 0,
    y: 0,
    w: 390,
    h: 120,
    fill: C.sage,
    name: 'Header',
  },
  {
    id: 'h_greet',
    type: 'text',
    x: 24,
    y: 56,
    w: 260,
    h: 24,
    text: 'Olá, bem-vinda',
    fontSize: 14,
    color: C.sageLight,
    name: 'Saudação',
  },
  {
    id: 'h_title',
    type: 'text',
    x: 24,
    y: 78,
    w: 300,
    h: 36,
    text: 'Natalia Farias',
    fontSize: 24,
    fontWeight: 700,
    color: C.white,
    name: 'Título',
  },
  {
    id: 'h_card1',
    type: 'rect',
    x: 24,
    y: 148,
    w: 164,
    h: 140,
    fill: C.white,
    cornerRadius: 20,
    stroke: C.border,
    strokeWidth: 1,
    name: 'Card serviços',
  },
  {
    id: 'h_card1_i',
    type: 'rect',
    x: 40,
    y: 164,
    w: 44,
    h: 44,
    fill: C.sageLight,
    cornerRadius: 12,
    name: 'Ícone',
  },
  {
    id: 'h_card1_t',
    type: 'text',
    x: 40,
    y: 220,
    w: 132,
    h: 24,
    text: 'Serviços',
    fontSize: 15,
    fontWeight: 700,
    color: C.text,
    name: 'Card1',
  },
  {
    id: 'h_card1_d',
    type: 'text',
    x: 40,
    y: 246,
    w: 132,
    h: 32,
    text: 'Individual · Online',
    fontSize: 12,
    color: C.muted,
    name: 'Card1 desc',
  },
  {
    id: 'h_card2',
    type: 'rect',
    x: 202,
    y: 148,
    w: 164,
    h: 140,
    fill: C.white,
    cornerRadius: 20,
    stroke: C.border,
    strokeWidth: 1,
    name: 'Card agendar',
  },
  {
    id: 'h_card2_i',
    type: 'rect',
    x: 218,
    y: 164,
    w: 44,
    h: 44,
    fill: '#F5EDE3',
    cornerRadius: 12,
    name: 'Ícone 2',
  },
  {
    id: 'h_card2_t',
    type: 'text',
    x: 218,
    y: 220,
    w: 132,
    h: 24,
    text: 'Agendar',
    fontSize: 15,
    fontWeight: 700,
    color: C.text,
    name: 'Card2',
  },
  {
    id: 'h_card2_d',
    type: 'text',
    x: 218,
    y: 246,
    w: 132,
    h: 32,
    text: 'Escolha horário',
    fontSize: 12,
    color: C.muted,
    name: 'Card2 desc',
  },
  {
    id: 'h_section',
    type: 'text',
    x: 24,
    y: 316,
    w: 240,
    h: 24,
    text: 'Próxima disponibilidade',
    fontSize: 16,
    fontWeight: 700,
    color: C.text,
    name: 'Seção',
  },
  {
    id: 'h_slot',
    type: 'rect',
    x: 24,
    y: 352,
    w: 342,
    h: 72,
    fill: C.white,
    cornerRadius: 16,
    stroke: C.sage,
    strokeWidth: 1,
    name: 'Slot',
  },
  {
    id: 'h_slot_t',
    type: 'text',
    x: 40,
    y: 368,
    w: 200,
    h: 22,
    text: 'Terça, 14:00',
    fontSize: 15,
    fontWeight: 600,
    color: C.text,
    name: 'Horário',
  },
  {
    id: 'h_slot_d',
    type: 'text',
    x: 40,
    y: 392,
    w: 220,
    h: 20,
    text: 'Consulta online · 50 min',
    fontSize: 12,
    color: C.muted,
    name: 'Slot desc',
  },
  {
    id: 'h_cta',
    type: 'button',
    x: 24,
    y: 760,
    w: 342,
    h: 56,
    label: 'Agendar consulta',
    fill: C.sage,
    textColor: C.white,
    cornerRadius: 16,
    fontSize: 16,
    fontWeight: 600,
    name: 'CTA',
  },
];

about.nodes = [
  {
    id: 'a_header',
    type: 'text',
    x: 24,
    y: 48,
    w: 342,
    h: 40,
    text: 'Sobre mim',
    fontSize: 28,
    fontWeight: 700,
    color: C.text,
    name: 'Título',
  },
  {
    id: 'a_photo',
    type: 'rect',
    x: 24,
    y: 108,
    w: 342,
    h: 200,
    fill: C.sageLight,
    cornerRadius: 20,
    name: 'Foto',
  },
  {
    id: 'a_bio',
    type: 'text',
    x: 24,
    y: 328,
    w: 342,
    h: 120,
    text: 'Sou Natalia Farias, psicóloga clínica. Atendo adultos em processos de ansiedade, autoestima e transições de vida — presencial e online.',
    fontSize: 15,
    fontWeight: 400,
    color: C.text,
    name: 'Bio',
  },
  {
    id: 'a_crp',
    type: 'rect',
    x: 24,
    y: 468,
    w: 342,
    h: 56,
    fill: C.white,
    cornerRadius: 12,
    stroke: C.border,
    strokeWidth: 1,
    name: 'CRP box',
  },
  {
    id: 'a_crp_t',
    type: 'text',
    x: 40,
    y: 484,
    w: 310,
    h: 24,
    text: 'CRP 00/00000 · Abordagem humanista',
    fontSize: 14,
    fontWeight: 600,
    color: C.sageDark,
    name: 'CRP',
  },
  {
    id: 'a_values',
    type: 'text',
    x: 24,
    y: 552,
    w: 342,
    h: 80,
    text: 'Ética · Escuta acolhedora · Sigilo · Sem julgamentos',
    fontSize: 14,
    color: C.muted,
    name: 'Valores',
  },
];

services.nodes = [
  {
    id: 's_title',
    type: 'text',
    x: 24,
    y: 48,
    w: 342,
    h: 40,
    text: 'Serviços',
    fontSize: 28,
    fontWeight: 700,
    color: C.text,
    name: 'Título',
  },
  {
    id: 's1',
    type: 'rect',
    x: 24,
    y: 108,
    w: 342,
    h: 100,
    fill: C.white,
    cornerRadius: 16,
    stroke: C.border,
    strokeWidth: 1,
    name: 'Serviço 1',
  },
  {
    id: 's1_t',
    type: 'text',
    x: 40,
    y: 124,
    w: 300,
    h: 24,
    text: 'Terapia individual',
    fontSize: 16,
    fontWeight: 700,
    color: C.text,
    name: 'S1 título',
  },
  {
    id: 's1_d',
    type: 'text',
    x: 40,
    y: 152,
    w: 300,
    h: 44,
    text: 'Sessões de 50 min · Presencial ou online',
    fontSize: 13,
    color: C.muted,
    name: 'S1 desc',
  },
  {
    id: 's2',
    type: 'rect',
    x: 24,
    y: 224,
    w: 342,
    h: 100,
    fill: C.white,
    cornerRadius: 16,
    stroke: C.border,
    strokeWidth: 1,
    name: 'Serviço 2',
  },
  {
    id: 's2_t',
    type: 'text',
    x: 40,
    y: 240,
    w: 300,
    h: 24,
    text: 'Primeira consulta',
    fontSize: 16,
    fontWeight: 700,
    color: C.text,
    name: 'S2 título',
  },
  {
    id: 's2_d',
    type: 'text',
    x: 40,
    y: 268,
    w: 300,
    h: 44,
    text: 'Conversa inicial para alinharmos expectativas',
    fontSize: 13,
    color: C.muted,
    name: 'S2 desc',
  },
  {
    id: 's3',
    type: 'rect',
    x: 24,
    y: 340,
    w: 342,
    h: 100,
    fill: C.white,
    cornerRadius: 16,
    stroke: C.border,
    strokeWidth: 1,
    name: 'Serviço 3',
  },
  {
    id: 's3_t',
    type: 'text',
    x: 40,
    y: 356,
    w: 300,
    h: 24,
    text: 'Orientação parental',
    fontSize: 16,
    fontWeight: 700,
    color: C.text,
    name: 'S3 título',
  },
  {
    id: 's3_d',
    type: 'text',
    x: 40,
    y: 384,
    w: 300,
    h: 44,
    text: 'Apoio a pais e cuidadores',
    fontSize: 13,
    color: C.muted,
    name: 'S3 desc',
  },
];

book.nodes = [
  {
    id: 'b_title',
    type: 'text',
    x: 24,
    y: 48,
    w: 342,
    h: 40,
    text: 'Agendar consulta',
    fontSize: 28,
    fontWeight: 700,
    color: C.text,
    name: 'Título',
  },
  {
    id: 'b_sub',
    type: 'text',
    x: 24,
    y: 92,
    w: 342,
    h: 40,
    text: 'Escolha o tipo e o melhor horário para você.',
    fontSize: 14,
    color: C.muted,
    name: 'Subtítulo',
  },
  {
    id: 'b_field1',
    type: 'rect',
    x: 24,
    y: 160,
    w: 342,
    h: 52,
    fill: C.white,
    cornerRadius: 12,
    stroke: C.border,
    strokeWidth: 1,
    name: 'Campo nome',
  },
  {
    id: 'b_field1_l',
    type: 'text',
    x: 40,
    y: 176,
    w: 200,
    h: 20,
    text: 'Seu nome',
    fontSize: 15,
    color: C.muted,
    name: 'Label nome',
  },
  {
    id: 'b_field2',
    type: 'rect',
    x: 24,
    y: 228,
    w: 342,
    h: 52,
    fill: C.white,
    cornerRadius: 12,
    stroke: C.border,
    strokeWidth: 1,
    name: 'Campo email',
  },
  {
    id: 'b_field2_l',
    type: 'text',
    x: 40,
    y: 244,
    w: 200,
    h: 20,
    text: 'E-mail',
    fontSize: 15,
    color: C.muted,
    name: 'Label email',
  },
  {
    id: 'b_pills',
    type: 'text',
    x: 24,
    y: 300,
    w: 342,
    h: 24,
    text: 'Modalidade',
    fontSize: 14,
    fontWeight: 600,
    color: C.text,
    name: 'Modalidade label',
  },
  {
    id: 'b_pill1',
    type: 'button',
    x: 24,
    y: 332,
    w: 160,
    h: 44,
    label: 'Online',
    fill: C.sage,
    textColor: C.white,
    cornerRadius: 22,
    fontSize: 14,
    fontWeight: 600,
    name: 'Pill online',
  },
  {
    id: 'b_pill2',
    type: 'button',
    x: 196,
    y: 332,
    w: 170,
    h: 44,
    label: 'Presencial',
    fill: C.white,
    textColor: C.sage,
    cornerRadius: 22,
    fontSize: 14,
    fontWeight: 600,
    stroke: C.sage,
    strokeWidth: 1,
    name: 'Pill presencial',
  },
  {
    id: 'b_cta',
    type: 'button',
    x: 24,
    y: 760,
    w: 342,
    h: 56,
    label: 'Confirmar agendamento',
    fill: C.sage,
    textColor: C.white,
    cornerRadius: 16,
    fontSize: 16,
    fontWeight: 600,
    name: 'CTA agendar',
  },
];

contact.nodes = [
  {
    id: 'c_title',
    type: 'text',
    x: 24,
    y: 48,
    w: 342,
    h: 40,
    text: 'Contato',
    fontSize: 28,
    fontWeight: 700,
    color: C.text,
    name: 'Título',
  },
  {
    id: 'c_card',
    type: 'rect',
    x: 24,
    y: 108,
    w: 342,
    h: 200,
    fill: C.sage,
    cornerRadius: 20,
    name: 'Card contato',
  },
  {
    id: 'c_name',
    type: 'text',
    x: 40,
    y: 132,
    w: 310,
    h: 32,
    text: 'Natalia Farias',
    fontSize: 22,
    fontWeight: 700,
    color: C.white,
    name: 'Nome',
  },
  {
    id: 'c_email',
    type: 'text',
    x: 40,
    y: 172,
    w: 310,
    h: 24,
    text: 'contato@nataliafarias.psi',
    fontSize: 14,
    color: C.sageLight,
    name: 'Email',
  },
  {
    id: 'c_phone',
    type: 'text',
    x: 40,
    y: 204,
    w: 310,
    h: 24,
    text: '(00) 00000-0000',
    fontSize: 14,
    color: C.sageLight,
    name: 'Telefone',
  },
  {
    id: 'c_wa',
    type: 'button',
    x: 40,
    y: 248,
    w: 310,
    h: 48,
    label: 'WhatsApp',
    fill: C.white,
    textColor: C.sageDark,
    cornerRadius: 14,
    fontSize: 15,
    fontWeight: 600,
    name: 'WhatsApp',
  },
  {
    id: 'c_ig',
    type: 'text',
    x: 24,
    y: 340,
    w: 342,
    h: 24,
    text: '@nataliafarias.psi',
    fontSize: 15,
    fontWeight: 600,
    color: C.sage,
    align: 'center',
    name: 'Instagram',
  },
];

// Componente: botão primário (a partir do CTA da welcome)
const compResult = createComponentFromNodes(welcome.nodes, ['w_cta'], 'Button / Primary');
if (!compResult.component || !compResult.mainNode) {
  throw new Error('Falha ao criar componente Button / Primary');
}
welcome.nodes = compResult.remainingNodes;
board.components.push(compResult.component);

const compId = compResult.component.id;
const mainId = compResult.mainNode.id;

// Instância no home
home.nodes.push(createInstance(compResult.component, undefined, 24, 760));

// Protótipo (triggerNodeId aponta para o main do componente na welcome)
board.prototypes = [
  {
    id: cryptoRandomId(),
    fromScreenId: welcome.id,
    triggerNodeId: mainId,
    toScreenId: home.id,
    transition: 'dissolve',
  },
  {
    id: cryptoRandomId(),
    fromScreenId: welcome.id,
    triggerNodeId: 'w_cta2',
    toScreenId: book.id,
    transition: 'dissolve',
  },
  {
    id: cryptoRandomId(),
    fromScreenId: home.id,
    triggerNodeId: 'h_card1',
    toScreenId: services.id,
    transition: 'instant',
  },
  {
    id: cryptoRandomId(),
    fromScreenId: home.id,
    triggerNodeId: 'h_card2',
    toScreenId: book.id,
    transition: 'instant',
  },
  {
    id: cryptoRandomId(),
    fromScreenId: services.id,
    triggerNodeId: 's3',
    toScreenId: book.id,
    transition: 'dissolve',
  },
];

// Comentários (feedback de design)
board.comments = [
  {
    id: cryptoRandomId(),
    screenId: welcome.id,
    x: 200,
    y: 140,
    text: 'Trocar por foto profissional da Natalia',
    resolved: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: cryptoRandomId(),
    screenId: book.id,
    x: 180,
    y: 400,
    text: 'Integrar calendário real na fase 2',
    resolved: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: cryptoRandomId(),
    screenId: about.id,
    x: 120,
    y: 200,
    text: 'CRP real + mini bio LinkedIn',
    resolved: false,
    createdAt: new Date().toISOString(),
  },
];

// Constraints no CTA welcome (pin bottom)
const wCta = welcome.nodes.find((n) => n.id === mainId || n.id === 'w_cta');
if (wCta) {
  wCta.constraints = { left: true, right: true, top: false, bottom: true };
}

board = syncAllComponentDefs(scrubBoardRefs(board));
writeBoard(board, path);

console.log(JSON.stringify({
  ok: true,
  projectId: PROJECT_ID,
  path,
  screens: board.screens.length,
  components: board.components.length,
  prototypes: board.prototypes.length,
  comments: board.comments.length,
}, null, 2));
